/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SCodeRouteImport } from './routes/s.$code'
import { Route as PromptsSlugRouteImport } from './routes/prompts.$slug'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSecurityRouteImport } from './routes/admin.security'
import { Route as AdminPromptsRouteImport } from './routes/admin.prompts'
import { Route as AdminDeployRouteImport } from './routes/admin.deploy'
import { Route as AdminCommentsRouteImport } from './routes/admin.comments'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminPromptsIndexRouteImport } from './routes/admin.prompts.index'
import { Route as ApiPublicVaultRouteImport } from './routes/api.public.vault'
import { Route as AdminPromptsIdRouteImport } from './routes/admin.prompts.$id'

const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SCodeRoute = SCodeRouteImport.update({
  id: '/s/$code',
  path: '/s/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsSlugRoute = PromptsSlugRouteImport.update({
  id: '/prompts/$slug',
  path: '/prompts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPromptsRoute = AdminPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDeployRoute = AdminDeployRouteImport.update({
  id: '/deploy',
  path: '/deploy',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommentsRoute = AdminCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPromptsIndexRoute = AdminPromptsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminPromptsRoute,
} as any)
const ApiPublicVaultRoute = ApiPublicVaultRouteImport.update({
  id: '/api/public/vault',
  path: '/api/public/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPromptsIdRoute = AdminPromptsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminPromptsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/browse': typeof BrowseRoute
  '/login': typeof LoginRoute
  '/saved': typeof SavedRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/deploy': typeof AdminDeployRoute
  '/admin/prompts': typeof AdminPromptsRouteWithChildren
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/p/$slug': typeof PSlugRoute
  '/prompts/$slug': typeof PromptsSlugRoute
  '/s/$code': typeof SCodeRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/prompts/$id': typeof AdminPromptsIdRoute
  '/api/public/vault': typeof ApiPublicVaultRoute
  '/admin/prompts/': typeof AdminPromptsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/login': typeof LoginRoute
  '/saved': typeof SavedRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/deploy': typeof AdminDeployRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/p/$slug': typeof PSlugRoute
  '/prompts/$slug': typeof PromptsSlugRoute
  '/s/$code': typeof SCodeRoute
  '/admin': typeof AdminIndexRoute
  '/admin/prompts/$id': typeof AdminPromptsIdRoute
  '/api/public/vault': typeof ApiPublicVaultRoute
  '/admin/prompts': typeof AdminPromptsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/browse': typeof BrowseRoute
  '/login': typeof LoginRoute
  '/saved': typeof SavedRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/deploy': typeof AdminDeployRoute
  '/admin/prompts': typeof AdminPromptsRouteWithChildren
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/p/$slug': typeof PSlugRoute
  '/prompts/$slug': typeof PromptsSlugRoute
  '/s/$code': typeof SCodeRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/prompts/$id': typeof AdminPromptsIdRoute
  '/api/public/vault': typeof ApiPublicVaultRoute
  '/admin/prompts/': typeof AdminPromptsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/browse'
    | '/login'
    | '/saved'
    | '/admin/categories'
    | '/admin/comments'
    | '/admin/deploy'
    | '/admin/prompts'
    | '/admin/security'
    | '/admin/settings'
    | '/p/$slug'
    | '/prompts/$slug'
    | '/s/$code'
    | '/admin/'
    | '/admin/prompts/$id'
    | '/api/public/vault'
    | '/admin/prompts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browse'
    | '/login'
    | '/saved'
    | '/admin/categories'
    | '/admin/comments'
    | '/admin/deploy'
    | '/admin/security'
    | '/admin/settings'
    | '/p/$slug'
    | '/prompts/$slug'
    | '/s/$code'
    | '/admin'
    | '/admin/prompts/$id'
    | '/api/public/vault'
    | '/admin/prompts'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/browse'
    | '/login'
    | '/saved'
    | '/admin/categories'
    | '/admin/comments'
    | '/admin/deploy'
    | '/admin/prompts'
    | '/admin/security'
    | '/admin/settings'
    | '/p/$slug'
    | '/prompts/$slug'
    | '/s/$code'
    | '/admin/'
    | '/admin/prompts/$id'
    | '/api/public/vault'
    | '/admin/prompts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BrowseRoute: typeof BrowseRoute
  LoginRoute: typeof LoginRoute
  SavedRoute: typeof SavedRoute
  PSlugRoute: typeof PSlugRoute
  PromptsSlugRoute: typeof PromptsSlugRoute
  SCodeRoute: typeof SCodeRoute
  ApiPublicVaultRoute: typeof ApiPublicVaultRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/s/$code': {
      id: '/s/$code'
      path: '/s/$code'
      fullPath: '/s/$code'
      preLoaderRoute: typeof SCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts/$slug': {
      id: '/prompts/$slug'
      path: '/prompts/$slug'
      fullPath: '/prompts/$slug'
      preLoaderRoute: typeof PromptsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/prompts': {
      id: '/admin/prompts'
      path: '/prompts'
      fullPath: '/admin/prompts'
      preLoaderRoute: typeof AdminPromptsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/deploy': {
      id: '/admin/deploy'
      path: '/deploy'
      fullPath: '/admin/deploy'
      preLoaderRoute: typeof AdminDeployRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comments': {
      id: '/admin/comments'
      path: '/comments'
      fullPath: '/admin/comments'
      preLoaderRoute: typeof AdminCommentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/prompts/': {
      id: '/admin/prompts/'
      path: '/'
      fullPath: '/admin/prompts/'
      preLoaderRoute: typeof AdminPromptsIndexRouteImport
      parentRoute: typeof AdminPromptsRoute
    }
    '/api/public/vault': {
      id: '/api/public/vault'
      path: '/api/public/vault'
      fullPath: '/api/public/vault'
      preLoaderRoute: typeof ApiPublicVaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/prompts/$id': {
      id: '/admin/prompts/$id'
      path: '/$id'
      fullPath: '/admin/prompts/$id'
      preLoaderRoute: typeof AdminPromptsIdRouteImport
      parentRoute: typeof AdminPromptsRoute
    }
  }
}

interface AdminPromptsRouteChildren {
  AdminPromptsIdRoute: typeof AdminPromptsIdRoute
  AdminPromptsIndexRoute: typeof AdminPromptsIndexRoute
}

const AdminPromptsRouteChildren: AdminPromptsRouteChildren = {
  AdminPromptsIdRoute: AdminPromptsIdRoute,
  AdminPromptsIndexRoute: AdminPromptsIndexRoute,
}

const AdminPromptsRouteWithChildren = AdminPromptsRoute._addFileChildren(
  AdminPromptsRouteChildren,
)

interface AdminRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCommentsRoute: typeof AdminCommentsRoute
  AdminDeployRoute: typeof AdminDeployRoute
  AdminPromptsRoute: typeof AdminPromptsRouteWithChildren
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCommentsRoute: AdminCommentsRoute,
  AdminDeployRoute: AdminDeployRoute,
  AdminPromptsRoute: AdminPromptsRouteWithChildren,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BrowseRoute: BrowseRoute,
  LoginRoute: LoginRoute,
  SavedRoute: SavedRoute,
  PSlugRoute: PSlugRoute,
  PromptsSlugRoute: PromptsSlugRoute,
  SCodeRoute: SCodeRoute,
  ApiPublicVaultRoute: ApiPublicVaultRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
